### ISSUE TITLE
FireStorm Source ToDo List

### ISSUE THREAD

**Issue by Sylica2013** [ProjectFireStorm/FireStorm#3]
These are the requirements that need to be done, before this project is playable by any standards.

- [ ] Update all DBC structures to TBC

- [ ] Update all required packets to TBC

- [ ] Update map extractors, so all maps can be made correctly

- [ ] Clean up project of commented code from Wotlk

- [ ] Update Spells and Encounters
