### ISSUE TITLE
FireStorm ToDo List

### ISSUE THREAD

**Issue by Sylica2013** [ProjectFireStorm/FireStorm#5]
Somethings that the core will see over time, to build our final project structure.

- [ ] Rebuild/Restructure Role Base Access Control (RBAC) System

- [ ] Restructure some commands

- [ ] Implement Character Transfer System

- [ ] Implement a Special Feature (secret)

- [ ] Restructure some game files
